" Name:         Solarized 8
" Description:  Precision colors for machines and people
" Authors:      Ethan Schoonover
" Maintainers:  Lifepillar <lifepillar@lifepillar.me>
" URLs:         https://github.com/lifepillar/vim-solarized8
" License:      OSI approved MIT license
" Last Updated: Sun Apr 23 23:53:35 2023

" Generated by Colortemplate v3.0.0-dev

hi clear
let g:colors_name = 'solarized8'

let s:t_Co = exists('&t_Co') && !has('gui_running') ? +&t_Co : -1

if &background == 'dark'
  let s:italics = get(g:, 'solarized_italics', 1) && ((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim'))
  let s:termtrans = get(g:, 'solarized_termtrans', 0) && !has('gui_running')
  let s:visibility = get(g:, 'solarized_visibility', 'normal')
  let s:vismap = {"normal": 0, "high": 1, "low": 2}
  let s:transvis = get(g:, 'solarized_termtrans', 0) + 2 * s:vismap[get(g:, 'solarized_visibility', 'normal')]
  let s:diffmode = get(g:, 'solarized_diffmode', 'normal')
  let s:stl = get(g:, 'solarized_statusline', 'normal')
  let s:oldcursor = get(g:, 'solarized_old_cursor_style', 0)

  let g:terminal_ansi_colors = ['#073642', '#dc322f', '#859900', '#b58900', '#268bd2', '#d33682', '#2aa198', '#eee8d5', '#002b36', '#cb4b16', '#586e75', '#657b83', '#839496', '#6c71c4', '#93a1a1', '#fdf6e3']

  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Constant
  hi! link Function Identifier
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Macro PreProc
  hi! link Number Constant
  hi! link Operator Statement
  hi! link PreCondit PreProc
  hi! link QuickFixLine Search
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link StorageClass Type
  hi! link String Constant
  hi! link Structure Type
  hi! link Tag Special
  hi! link TermCursor Cursor
  hi! link Typedef Type
  hi! link lCursor Cursor

  hi Normal guifg=#93a1a1 guibg=#002b36 guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#073642 guisp=NONE gui=NONE cterm=NONE
  hi CommandMode guifg=#d33682 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi Comment guifg=#586e75 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conceal guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#fdf6e3 guibg=#268bd2 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#073642 guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#073642 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#839496 guibg=#073642 guisp=NONE gui=bold cterm=bold
  hi DiffAdd guifg=#859900 guibg=#073642 guisp=#859900 gui=NONE cterm=NONE
  hi DiffChange guifg=#b58900 guibg=#073642 guisp=#b58900 gui=NONE cterm=NONE
  hi DiffDelete guifg=#dc322f guibg=#073642 guisp=NONE gui=bold cterm=bold
  hi DiffText guifg=#268bd2 guibg=#073642 guisp=#268bd2 gui=NONE cterm=NONE
  hi Directory guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=NONE guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#dc322f guibg=#fdf6e3 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#dc322f guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#839496 guibg=#073642 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#839496 guibg=#073642 guisp=#002b36 gui=bold cterm=bold
  hi Identifier guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#cb4b16 guibg=NONE guisp=NONE gui=standout cterm=standout
  hi InsertMode guifg=#2aa198 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi LineNr guifg=#657b83 guibg=#073642 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#fdf6e3 guibg=#073642 guisp=NONE gui=bold cterm=bold
  hi ModeMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#657b83 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi NormalMode guifg=#839496 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi Pmenu guifg=#93a1a1 guibg=#073642 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#586e75 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#eee8d5 guibg=#657b83 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#839496 guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#2aa198 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ReplaceMode guifg=#cb4b16 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi Search guifg=#b58900 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi SignColumn guifg=#839496 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#657b83 guibg=#073642 guisp=NONE gui=bold cterm=bold
  hi SpellBad guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
  hi SpellCap guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl cterm=undercurl
  hi SpellRare guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl cterm=undercurl
  hi Statement guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#839496 guibg=#073642 guisp=NONE gui=reverse cterm=reverse
  hi StatusLineNC guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse cterm=reverse
  hi TabLine guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse cterm=reverse
  hi TabLineFill guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse cterm=reverse
  hi TabLineSel guifg=#839496 guibg=#073642 guisp=NONE gui=reverse cterm=reverse
  hi TermCursorNC guifg=#002b36 guibg=#586e75 guisp=NONE gui=NONE cterm=NONE
  hi Terminal guifg=fg guibg=#002b36 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Todo guifg=#d33682 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ToolbarButton guifg=#93a1a1 guibg=#073642 guisp=NONE gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#073642 guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#073642 guibg=#586e75 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#586e75 guibg=#002b36 guisp=NONE gui=reverse cterm=reverse
  hi VisualMode guifg=#d33682 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#073642 guisp=NONE gui=reverse cterm=reverse
  hi WarningMsg guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WildMenu guifg=#eee8d5 guibg=#073642 guisp=NONE gui=reverse cterm=reverse

  if has('gui_running')
    if s:diffmode == "high"
      hi DiffAdd guifg=#859900 guibg=NONE guisp=NONE gui=reverse
      hi DiffChange guifg=#b58900 guibg=NONE guisp=NONE gui=reverse
      hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=reverse
      hi DiffText guifg=#268bd2 guibg=NONE guisp=NONE gui=reverse
    elseif s:diffmode == "low"
      hi DiffAdd guifg=#859900 guibg=NONE guisp=#859900 gui=NONE
      hi DiffChange guifg=#b58900 guibg=NONE guisp=#b58900 gui=NONE
      hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi DiffText guifg=#268bd2 guibg=NONE guisp=#268bd2 gui=NONE
    endif
    if s:italics == 0
      hi Comment gui=NONE
    endif
    if s:oldcursor == 1
      hi Cursor guifg=#002b36 guibg=#839496 guisp=NONE gui=NONE
    endif
    if s:stl == "flat"
      hi StatusLine guifg=#073642 guibg=#eee8d5 guisp=NONE gui=reverse
      hi StatusLineNC guifg=#073642 guibg=#93a1a1 guisp=NONE gui=reverse
      hi TabLine guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
      hi TabLineFill guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
      hi TabLineSel guifg=#eee8d5 guibg=#073642 guisp=NONE gui=NONE
      hi VertSplit guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
    elseif s:stl == "low"
      hi StatusLine guifg=#586e75 guibg=#eee8d5 guisp=NONE gui=reverse
      hi StatusLineNC guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
      hi TabLine guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
      hi TabLineFill guifg=#586e75 guibg=#073642 guisp=NONE gui=reverse
      hi TabLineSel guifg=#839496 guibg=#fdf6e3 guisp=NONE gui=reverse
      hi VertSplit guifg=#073642 guibg=#586e75 guisp=NONE gui=NONE
    endif
    if s:transvis == 1
      hi CursorLineNr guifg=#839496 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
    elseif s:transvis == 2
      hi CursorLineNr guifg=#cb4b16 guibg=#073642 guisp=NONE gui=bold
      hi LineNr guifg=#839496 guibg=#073642 guisp=NONE gui=NONE
    elseif s:transvis == 3
      hi CursorLineNr guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#839496 guibg=NONE guisp=NONE gui=NONE
    elseif s:transvis == 4
      hi CursorLineNr guifg=#586e75 guibg=#073642 guisp=NONE gui=bold
      hi LineNr guifg=#586e75 guibg=#073642 guisp=NONE gui=NONE
    elseif s:transvis == 5
      hi CursorLineNr guifg=#586e75 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#586e75 guibg=NONE guisp=NONE gui=NONE
    endif
    if s:visibility == "high"
      hi NonText guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
      hi SpecialKey guifg=#cb4b16 guibg=NONE guisp=NONE gui=reverse
      hi SpellBad guifg=#6c71c4 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi SpellCap guifg=#6c71c4 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi SpellLocal guifg=#b58900 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi SpellRare guifg=#2aa198 guibg=#fdf6e3 guisp=#dc322f gui=reverse,undercurl
      hi Title guifg=#b58900 guibg=NONE guisp=NONE gui=bold
    elseif s:visibility == "low"
      hi NonText guifg=#073642 guibg=NONE guisp=NONE gui=bold
      hi SpecialKey guifg=#073642 guibg=NONE guisp=NONE gui=reverse
      hi SpellBad guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl
      hi SpellCap guifg=#6c71c4 guibg=NONE guisp=#6c71c4 gui=undercurl
      hi SpellLocal guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl
      hi SpellRare guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl
      hi Title guifg=#586e75 guibg=NONE guisp=NONE gui=bold
    endif
  endif

  if s:t_Co >= 256
    hi Normal ctermfg=247 ctermbg=235 ctermul=NONE cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=236 ctermul=NONE cterm=NONE
    hi CommandMode ctermfg=162 ctermbg=230 ctermul=NONE cterm=reverse
    hi Comment ctermfg=242 ctermbg=NONE ctermul=NONE cterm=italic
    hi Conceal ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Constant ctermfg=37 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Cursor ctermfg=230 ctermbg=32 ctermul=NONE cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=236 ctermul=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg ctermul=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=236 ctermul=NONE cterm=NONE
    hi CursorLineNr ctermfg=246 ctermbg=236 ctermul=NONE cterm=bold
    hi DiffAdd ctermfg=106 ctermbg=236 ctermul=NONE cterm=NONE
    hi DiffChange ctermfg=136 ctermbg=236 ctermul=NONE cterm=NONE
    hi DiffDelete ctermfg=160 ctermbg=236 ctermul=NONE cterm=bold
    hi DiffText ctermfg=32 ctermbg=236 ctermul=NONE cterm=NONE
    hi Directory ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi Error ctermfg=160 ctermbg=230 ctermul=NONE cterm=bold,reverse
    hi ErrorMsg ctermfg=160 ctermbg=230 ctermul=NONE cterm=reverse
    hi FoldColumn ctermfg=246 ctermbg=236 ctermul=NONE cterm=NONE
    hi Folded ctermfg=246 ctermbg=236 ctermul=NONE cterm=bold
    hi Identifier ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi IncSearch ctermfg=166 ctermbg=NONE ctermul=NONE cterm=standout
    hi InsertMode ctermfg=37 ctermbg=230 ctermul=NONE cterm=reverse
    hi LineNr ctermfg=66 ctermbg=236 ctermul=NONE cterm=NONE
    hi MatchParen ctermfg=230 ctermbg=236 ctermul=NONE cterm=bold
    hi ModeMsg ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi MoreMsg ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi NonText ctermfg=66 ctermbg=NONE ctermul=NONE cterm=bold
    hi NormalMode ctermfg=246 ctermbg=230 ctermul=NONE cterm=reverse
    hi Pmenu ctermfg=247 ctermbg=236 ctermul=NONE cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=242 ctermul=NONE cterm=NONE
    hi PmenuSel ctermfg=254 ctermbg=66 ctermul=NONE cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=246 ctermul=NONE cterm=NONE
    hi PreProc ctermfg=166 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Question ctermfg=37 ctermbg=NONE ctermul=NONE cterm=bold
    hi ReplaceMode ctermfg=166 ctermbg=230 ctermul=NONE cterm=reverse
    hi Search ctermfg=136 ctermbg=NONE ctermul=NONE cterm=reverse
    hi SignColumn ctermfg=246 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Special ctermfg=166 ctermbg=NONE ctermul=NONE cterm=NONE
    hi SpecialKey ctermfg=66 ctermbg=236 ctermul=NONE cterm=bold
    hi SpellBad ctermfg=61 ctermbg=NONE ctermul=NONE cterm=underline
    hi SpellCap ctermfg=61 ctermbg=NONE ctermul=NONE cterm=underline
    hi SpellLocal ctermfg=136 ctermbg=NONE ctermul=NONE cterm=underline
    hi SpellRare ctermfg=37 ctermbg=NONE ctermul=NONE cterm=underline
    hi Statement ctermfg=106 ctermbg=NONE ctermul=NONE cterm=NONE
    hi StatusLine ctermfg=246 ctermbg=236 ctermul=NONE cterm=reverse
    hi StatusLineNC ctermfg=242 ctermbg=236 ctermul=NONE cterm=reverse
    hi TabLine ctermfg=242 ctermbg=236 ctermul=NONE cterm=reverse
    hi TabLineFill ctermfg=242 ctermbg=236 ctermul=NONE cterm=reverse
    hi TabLineSel ctermfg=246 ctermbg=236 ctermul=NONE cterm=reverse
    hi TermCursorNC ctermfg=235 ctermbg=242 ctermul=NONE cterm=NONE
    hi Terminal ctermfg=fg ctermbg=235 ctermul=NONE cterm=NONE
    hi Title ctermfg=166 ctermbg=NONE ctermul=NONE cterm=bold
    hi Todo ctermfg=162 ctermbg=NONE ctermul=NONE cterm=bold
    hi ToolbarButton ctermfg=247 ctermbg=236 ctermul=NONE cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=236 ctermul=NONE cterm=NONE
    hi Type ctermfg=136 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Underlined ctermfg=61 ctermbg=NONE ctermul=NONE cterm=NONE
    hi VertSplit ctermfg=236 ctermbg=242 ctermul=NONE cterm=NONE
    hi Visual ctermfg=242 ctermbg=235 ctermul=NONE cterm=reverse
    hi VisualMode ctermfg=162 ctermbg=230 ctermul=NONE cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=236 ctermul=NONE cterm=reverse
    hi WarningMsg ctermfg=166 ctermbg=NONE ctermul=NONE cterm=bold
    hi WildMenu ctermfg=254 ctermbg=236 ctermul=NONE cterm=reverse
    if s:diffmode == "high"
      hi DiffAdd ctermfg=106 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffChange ctermfg=136 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffDelete ctermfg=160 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffText ctermfg=32 ctermbg=NONE ctermul=NONE cterm=reverse
    elseif s:diffmode == "low"
      hi DiffAdd ctermfg=106 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffChange ctermfg=136 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffDelete ctermfg=160 ctermbg=NONE ctermul=NONE cterm=bold
      hi DiffText ctermfg=32 ctermbg=NONE ctermul=32 cterm=NONE
    endif
    if s:italics == 0
      hi Comment cterm=NONE
    endif
    if s:oldcursor == 1
      hi Cursor ctermfg=235 ctermbg=246 ctermul=NONE cterm=NONE
    endif
    if s:stl == "flat"
      hi StatusLine ctermfg=236 ctermbg=254 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=236 ctermbg=247 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=242 ctermbg=236 ctermul=NONE cterm=NONE
      hi TabLineFill ctermfg=242 ctermbg=236 ctermul=NONE cterm=NONE
      hi TabLineSel ctermfg=254 ctermbg=236 ctermul=NONE cterm=NONE
      hi VertSplit ctermfg=242 ctermbg=236 ctermul=NONE cterm=NONE
    elseif s:stl == "low"
      hi StatusLine ctermfg=242 ctermbg=254 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=242 ctermbg=236 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=242 ctermbg=236 ctermul=NONE cterm=reverse
      hi TabLineFill ctermfg=242 ctermbg=236 ctermul=NONE cterm=reverse
      hi TabLineSel ctermfg=246 ctermbg=230 ctermul=NONE cterm=reverse
      hi VertSplit ctermfg=236 ctermbg=242 ctermul=NONE cterm=NONE
    endif
    if s:termtrans == 1
      hi Normal ctermfg=247 ctermbg=NONE ctermul=NONE cterm=NONE
      hi FoldColumn ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE
      hi Folded ctermfg=fg ctermbg=NONE ctermul=NONE cterm=bold
      hi Terminal ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE
      hi ToolbarButton ctermfg=247 ctermbg=NONE ctermul=NONE cterm=bold
      hi ToolbarLine ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:transvis == 1
      hi CursorLineNr ctermfg=246 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=66 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 2
      hi CursorLineNr ctermfg=166 ctermbg=236 ctermul=NONE cterm=bold
      hi LineNr ctermfg=246 ctermbg=236 ctermul=NONE cterm=NONE
    elseif s:transvis == 3
      hi CursorLineNr ctermfg=166 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=246 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 4
      hi CursorLineNr ctermfg=242 ctermbg=236 ctermul=NONE cterm=bold
      hi LineNr ctermfg=242 ctermbg=236 ctermul=NONE cterm=NONE
    elseif s:transvis == 5
      hi CursorLineNr ctermfg=242 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=242 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:visibility == "high"
      hi NonText ctermfg=166 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=166 ctermbg=NONE ctermul=NONE cterm=reverse
      hi SpellBad ctermfg=61 ctermbg=230 ctermul=NONE cterm=reverse,underline
      hi SpellCap ctermfg=61 ctermbg=230 ctermul=NONE cterm=reverse,underline
      hi SpellLocal ctermfg=136 ctermbg=230 ctermul=NONE cterm=reverse,underline
      hi SpellRare ctermfg=37 ctermbg=230 ctermul=NONE cterm=reverse,underline
      hi Title ctermfg=136 ctermbg=NONE ctermul=NONE cterm=bold
    elseif s:visibility == "low"
      hi NonText ctermfg=236 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=236 ctermbg=NONE ctermul=NONE cterm=reverse
      hi SpellBad ctermfg=61 ctermbg=NONE ctermul=NONE cterm=underline
      hi SpellCap ctermfg=61 ctermbg=NONE ctermul=NONE cterm=underline
      hi SpellLocal ctermfg=136 ctermbg=NONE ctermul=NONE cterm=underline
      hi SpellRare ctermfg=37 ctermbg=NONE ctermul=NONE cterm=underline
      hi Title ctermfg=242 ctermbg=NONE ctermul=NONE cterm=bold
    endif
    unlet s:t_Co
    unlet s:italics
    unlet s:termtrans
    unlet s:visibility
    unlet s:vismap
    unlet s:transvis
    unlet s:diffmode
    unlet s:stl
    unlet s:oldcursor
    finish
  endif

  if s:t_Co >= 16
    hi Normal ctermfg=14 ctermbg=8 ctermul=NONE cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=0 ctermul=NONE cterm=NONE
    hi CommandMode ctermfg=5 ctermbg=15 ctermul=NONE cterm=reverse
    hi Comment ctermfg=10 ctermbg=NONE ctermul=NONE cterm=italic
    hi Conceal ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Constant ctermfg=6 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Cursor ctermfg=15 ctermbg=4 ctermul=NONE cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=0 ctermul=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg ctermul=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=0 ctermul=NONE cterm=NONE
    hi CursorLineNr ctermfg=12 ctermbg=0 ctermul=NONE cterm=bold
    hi DiffAdd ctermfg=2 ctermbg=0 ctermul=NONE cterm=NONE
    hi DiffChange ctermfg=3 ctermbg=0 ctermul=NONE cterm=NONE
    hi DiffDelete ctermfg=1 ctermbg=0 ctermul=NONE cterm=bold
    hi DiffText ctermfg=4 ctermbg=0 ctermul=NONE cterm=NONE
    hi Directory ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi Error ctermfg=1 ctermbg=15 ctermul=NONE cterm=bold,reverse
    hi ErrorMsg ctermfg=1 ctermbg=15 ctermul=NONE cterm=reverse
    hi FoldColumn ctermfg=12 ctermbg=0 ctermul=NONE cterm=NONE
    hi Folded ctermfg=12 ctermbg=0 ctermul=NONE cterm=bold
    hi Identifier ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi IncSearch ctermfg=9 ctermbg=NONE ctermul=NONE cterm=standout
    hi InsertMode ctermfg=6 ctermbg=15 ctermul=NONE cterm=reverse
    hi LineNr ctermfg=11 ctermbg=0 ctermul=NONE cterm=NONE
    hi MatchParen ctermfg=15 ctermbg=0 ctermul=NONE cterm=bold
    hi ModeMsg ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi MoreMsg ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi NonText ctermfg=11 ctermbg=NONE ctermul=NONE cterm=bold
    hi NormalMode ctermfg=12 ctermbg=15 ctermul=NONE cterm=reverse
    hi Pmenu ctermfg=14 ctermbg=0 ctermul=NONE cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=10 ctermul=NONE cterm=NONE
    hi PmenuSel ctermfg=7 ctermbg=11 ctermul=NONE cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=12 ctermul=NONE cterm=NONE
    hi PreProc ctermfg=9 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Question ctermfg=6 ctermbg=NONE ctermul=NONE cterm=bold
    hi ReplaceMode ctermfg=9 ctermbg=15 ctermul=NONE cterm=reverse
    hi Search ctermfg=3 ctermbg=NONE ctermul=NONE cterm=reverse
    hi SignColumn ctermfg=12 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Special ctermfg=9 ctermbg=NONE ctermul=NONE cterm=NONE
    hi SpecialKey ctermfg=11 ctermbg=0 ctermul=NONE cterm=bold
    hi SpellBad ctermfg=13 ctermbg=NONE ctermul=NONE cterm=underline
    hi SpellCap ctermfg=13 ctermbg=NONE ctermul=NONE cterm=underline
    hi SpellLocal ctermfg=3 ctermbg=NONE ctermul=NONE cterm=underline
    hi SpellRare ctermfg=6 ctermbg=NONE ctermul=NONE cterm=underline
    hi Statement ctermfg=2 ctermbg=NONE ctermul=NONE cterm=NONE
    hi StatusLine ctermfg=12 ctermbg=0 ctermul=NONE cterm=reverse
    hi StatusLineNC ctermfg=10 ctermbg=0 ctermul=NONE cterm=reverse
    hi TabLine ctermfg=10 ctermbg=0 ctermul=NONE cterm=reverse
    hi TabLineFill ctermfg=10 ctermbg=0 ctermul=NONE cterm=reverse
    hi TabLineSel ctermfg=12 ctermbg=0 ctermul=NONE cterm=reverse
    hi TermCursorNC ctermfg=8 ctermbg=10 ctermul=NONE cterm=NONE
    hi Terminal ctermfg=fg ctermbg=8 ctermul=NONE cterm=NONE
    hi Title ctermfg=9 ctermbg=NONE ctermul=NONE cterm=bold
    hi Todo ctermfg=5 ctermbg=NONE ctermul=NONE cterm=bold
    hi ToolbarButton ctermfg=14 ctermbg=0 ctermul=NONE cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=0 ctermul=NONE cterm=NONE
    hi Type ctermfg=3 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Underlined ctermfg=13 ctermbg=NONE ctermul=NONE cterm=NONE
    hi VertSplit ctermfg=0 ctermbg=10 ctermul=NONE cterm=NONE
    hi Visual ctermfg=10 ctermbg=8 ctermul=NONE cterm=reverse
    hi VisualMode ctermfg=5 ctermbg=15 ctermul=NONE cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=0 ctermul=NONE cterm=reverse
    hi WarningMsg ctermfg=9 ctermbg=NONE ctermul=NONE cterm=bold
    hi WildMenu ctermfg=7 ctermbg=0 ctermul=NONE cterm=reverse
    if s:diffmode == "high"
      hi DiffAdd ctermfg=2 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffChange ctermfg=3 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffDelete ctermfg=1 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffText ctermfg=4 ctermbg=NONE ctermul=NONE cterm=reverse
    elseif s:diffmode == "low"
      hi DiffAdd ctermfg=2 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffChange ctermfg=3 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffDelete ctermfg=1 ctermbg=NONE ctermul=NONE cterm=bold
      hi DiffText ctermfg=4 ctermbg=NONE ctermul=4 cterm=NONE
    endif
    if s:italics == 0
      hi Comment cterm=NONE
    endif
    if s:oldcursor == 1
      hi Cursor ctermfg=8 ctermbg=12 ctermul=NONE cterm=NONE
    endif
    if s:stl == "flat"
      hi StatusLine ctermfg=0 ctermbg=7 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=0 ctermbg=14 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=10 ctermbg=0 ctermul=NONE cterm=NONE
      hi TabLineFill ctermfg=10 ctermbg=0 ctermul=NONE cterm=NONE
      hi TabLineSel ctermfg=7 ctermbg=0 ctermul=NONE cterm=NONE
      hi VertSplit ctermfg=10 ctermbg=0 ctermul=NONE cterm=NONE
    elseif s:stl == "low"
      hi StatusLine ctermfg=10 ctermbg=7 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=10 ctermbg=0 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=10 ctermbg=0 ctermul=NONE cterm=reverse
      hi TabLineFill ctermfg=10 ctermbg=0 ctermul=NONE cterm=reverse
      hi TabLineSel ctermfg=12 ctermbg=15 ctermul=NONE cterm=reverse
      hi VertSplit ctermfg=0 ctermbg=10 ctermul=NONE cterm=NONE
    endif
    if s:termtrans == 1
      hi Normal ctermfg=14 ctermbg=NONE ctermul=NONE cterm=NONE
      hi FoldColumn ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE
      hi Folded ctermfg=fg ctermbg=NONE ctermul=NONE cterm=bold
      hi Terminal ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE
      hi ToolbarButton ctermfg=14 ctermbg=NONE ctermul=NONE cterm=bold
      hi ToolbarLine ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:transvis == 1
      hi CursorLineNr ctermfg=12 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=11 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 2
      hi CursorLineNr ctermfg=9 ctermbg=0 ctermul=NONE cterm=bold
      hi LineNr ctermfg=12 ctermbg=0 ctermul=NONE cterm=NONE
    elseif s:transvis == 3
      hi CursorLineNr ctermfg=9 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=12 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 4
      hi CursorLineNr ctermfg=10 ctermbg=0 ctermul=NONE cterm=bold
      hi LineNr ctermfg=10 ctermbg=0 ctermul=NONE cterm=NONE
    elseif s:transvis == 5
      hi CursorLineNr ctermfg=10 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=10 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:visibility == "high"
      hi NonText ctermfg=9 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=9 ctermbg=NONE ctermul=NONE cterm=reverse
      hi SpellBad ctermfg=13 ctermbg=15 ctermul=NONE cterm=reverse,underline
      hi SpellCap ctermfg=13 ctermbg=15 ctermul=NONE cterm=reverse,underline
      hi SpellLocal ctermfg=3 ctermbg=15 ctermul=NONE cterm=reverse,underline
      hi SpellRare ctermfg=6 ctermbg=15 ctermul=NONE cterm=reverse,underline
      hi Title ctermfg=3 ctermbg=NONE ctermul=NONE cterm=bold
    elseif s:visibility == "low"
      hi NonText ctermfg=0 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=0 ctermbg=NONE ctermul=NONE cterm=reverse
      hi SpellBad ctermfg=13 ctermbg=NONE ctermul=NONE cterm=underline
      hi SpellCap ctermfg=13 ctermbg=NONE ctermul=NONE cterm=underline
      hi SpellLocal ctermfg=3 ctermbg=NONE ctermul=NONE cterm=underline
      hi SpellRare ctermfg=6 ctermbg=NONE ctermul=NONE cterm=underline
      hi Title ctermfg=10 ctermbg=NONE ctermul=NONE cterm=bold
    endif
    unlet s:t_Co
    unlet s:italics
    unlet s:termtrans
    unlet s:visibility
    unlet s:vismap
    unlet s:transvis
    unlet s:diffmode
    unlet s:stl
    unlet s:oldcursor
    finish
  endif

  if s:t_Co >= 0
    hi Normal term=NONE
    hi ColorColumn term=reverse
    hi CommandMode term=reverse
    hi Comment term=italic
    hi Conceal term=NONE
    hi Constant term=bold,italic
    hi Cursor term=NONE
    hi CursorColumn term=reverse
    hi CursorIM term=NONE
    hi CursorLine term=underline
    hi CursorLineNr term=bold,italic,reverse,underline
    hi DiffAdd term=reverse,underline
    hi DiffChange term=reverse,underline
    hi DiffDelete term=reverse,underline
    hi DiffText term=bold,reverse,underline
    hi Directory term=NONE
    hi EndOfBuffer term=NONE
    hi Error term=reverse
    hi ErrorMsg term=bold,italic,reverse
    hi FoldColumn term=reverse
    hi Folded term=italic,reverse,underline
    hi Identifier term=italic
    hi Ignore term=NONE
    hi IncSearch term=bold,italic,reverse
    hi InsertMode term=reverse
    hi LineNr term=reverse
    hi MatchParen term=bold,underline
    hi ModeMsg term=NONE
    hi MoreMsg term=NONE
    hi NonText term=NONE
    hi NormalMode term=reverse
    hi Pmenu term=reverse
    hi PmenuSbar term=NONE
    hi PmenuSel term=NONE
    hi PmenuThumb term=NONE
    hi PreProc term=italic
    hi Question term=standout
    hi ReplaceMode term=reverse
    hi Search term=italic,underline
    hi SignColumn term=reverse
    hi Special term=bold,italic
    hi SpecialKey term=bold
    hi SpellBad term=italic,underline
    hi SpellCap term=italic,underline
    hi SpellLocal term=italic,underline
    hi SpellRare term=italic,underline
    hi Statement term=bold
    hi StatusLine term=bold,reverse
    hi StatusLineNC term=reverse
    hi TabLine term=italic,reverse,underline
    hi TabLineFill term=reverse,underline
    hi TabLineSel term=bold
    hi TermCursorNC term=NONE
    hi Terminal term=NONE
    hi Title term=bold
    hi Todo term=bold,underline
    hi ToolbarButton term=bold,reverse
    hi ToolbarLine term=reverse
    hi Type term=bold
    hi Underlined term=underline
    hi VertSplit term=reverse
    hi Visual term=reverse
    hi VisualMode term=reverse
    hi VisualNOS term=NONE
    hi WarningMsg term=standout
    hi WildMenu term=bold
    if s:diffmode == "high"
      hi DiffAdd term=reverse
      hi DiffChange term=reverse
      hi DiffDelete term=reverse
      hi DiffText term=reverse
    elseif s:diffmode == "low"
      hi DiffDelete term=bold
    endif
    if s:italics == 0
      hi Comment term=NONE
    endif
    if s:oldcursor == 1
      hi Cursor term=NONE
    endif
    if s:stl == "flat"
      hi StatusLine term=reverse
      hi StatusLineNC term=reverse
      hi TabLine term=NONE
      hi TabLineFill term=NONE
      hi TabLineSel term=NONE
      hi VertSplit term=NONE
    elseif s:stl == "low"
      hi StatusLine term=reverse
      hi StatusLineNC term=reverse
      hi TabLine term=reverse
      hi TabLineFill term=reverse
      hi TabLineSel term=reverse
      hi VertSplit term=NONE
    endif
    if s:transvis == 1
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 2
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 3
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 4
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 5
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    endif
    if s:visibility == "high"
      hi NonText term=bold
      hi SpecialKey term=reverse
      hi Title term=bold
    elseif s:visibility == "low"
      hi NonText term=bold
      hi SpecialKey term=reverse
      hi Title term=bold
    endif
    unlet s:t_Co
    unlet s:italics
    unlet s:termtrans
    unlet s:visibility
    unlet s:vismap
    unlet s:transvis
    unlet s:diffmode
    unlet s:stl
    unlet s:oldcursor
    finish
  endif
endif

if &background == 'light'
  let s:italics = get(g:, 'solarized_italics', 1) && ((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim'))
  let s:termtrans = get(g:, 'solarized_termtrans', 0) && !has('gui_running')
  let s:visibility = get(g:, 'solarized_visibility', 'normal')
  let s:vismap = {"normal": 0, "high": 1, "low": 2}
  let s:transvis = get(g:, 'solarized_termtrans', 0) + 2 * s:vismap[get(g:, 'solarized_visibility', 'normal')]
  let s:diffmode = get(g:, 'solarized_diffmode', 'normal')
  let s:stl = get(g:, 'solarized_statusline', 'normal')
  let s:viscurs = get(g:, 'solarized_old_cursor_style', 0) + 2 * s:vismap[get(g:, 'solarized_visibility', 'normal')]

  let g:terminal_ansi_colors = ['#073642', '#dc322f', '#859900', '#b58900', '#268bd2', '#d33682', '#2aa198', '#eee8d5', '#002b36', '#cb4b16', '#586e75', '#657b83', '#839496', '#6c71c4', '#93a1a1', '#fdf6e3']

  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Conditional Statement
  hi! link Debug Special
  hi! link Define PreProc
  hi! link Delimiter Special
  hi! link Exception Statement
  hi! link Float Constant
  hi! link Function Identifier
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Macro PreProc
  hi! link Number Constant
  hi! link Operator Statement
  hi! link PreCondit PreProc
  hi! link QuickFixLine Search
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link StorageClass Type
  hi! link String Constant
  hi! link Structure Type
  hi! link Tag Special
  hi! link TermCursor Cursor
  hi! link Typedef Type
  hi! link lCursor Cursor

  hi Normal guifg=#586e75 guibg=#fdf6e3 guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#eee8d5 guisp=NONE gui=NONE cterm=NONE
  hi CommandMode guifg=#d33682 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi Comment guifg=#93a1a1 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Conceal guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Constant guifg=#2aa198 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#fdf6e3 guibg=#cb4b16 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#eee8d5 guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#eee8d5 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#657b83 guibg=#eee8d5 guisp=NONE gui=bold cterm=bold
  hi DiffAdd guifg=#859900 guibg=#eee8d5 guisp=#859900 gui=NONE cterm=NONE
  hi DiffChange guifg=#b58900 guibg=#eee8d5 guisp=#b58900 gui=NONE cterm=NONE
  hi DiffDelete guifg=#dc322f guibg=#eee8d5 guisp=NONE gui=bold cterm=bold
  hi DiffText guifg=#268bd2 guibg=#eee8d5 guisp=#268bd2 gui=NONE cterm=NONE
  hi Directory guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=NONE guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#dc322f guibg=#fdf6e3 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi ErrorMsg guifg=#dc322f guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi FoldColumn guifg=#657b83 guibg=#eee8d5 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#657b83 guibg=#eee8d5 guisp=#fdf6e3 gui=bold cterm=bold
  hi Identifier guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#cb4b16 guibg=NONE guisp=NONE gui=standout cterm=standout
  hi InsertMode guifg=#2aa198 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi LineNr guifg=#839496 guibg=#eee8d5 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#dc322f guibg=#eee8d5 guisp=NONE gui=bold,underline cterm=bold,underline
  hi ModeMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#268bd2 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#839496 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi NormalMode guifg=#586e75 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi Pmenu guifg=#586e75 guibg=#eee8d5 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=#93a1a1 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#eee8d5 guibg=#839496 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#657b83 guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#2aa198 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ReplaceMode guifg=#cb4b16 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi Search guifg=#b58900 guibg=NONE guisp=NONE gui=reverse cterm=reverse
  hi SignColumn guifg=#657b83 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#cb4b16 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#839496 guibg=#eee8d5 guisp=NONE gui=bold cterm=bold
  hi SpellBad guifg=#d33682 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
  hi SpellCap guifg=#d33682 guibg=NONE guisp=#6c71c4 gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl cterm=undercurl
  hi SpellRare guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl cterm=undercurl
  hi Statement guifg=#859900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#586e75 guibg=#eee8d5 guisp=NONE gui=reverse cterm=reverse
  hi StatusLineNC guifg=#839496 guibg=#eee8d5 guisp=NONE gui=reverse cterm=reverse
  hi TabLine guifg=#839496 guibg=#eee8d5 guisp=NONE gui=reverse cterm=reverse
  hi TabLineFill guifg=#839496 guibg=#eee8d5 guisp=NONE gui=reverse cterm=reverse
  hi TabLineSel guifg=#586e75 guibg=#eee8d5 guisp=NONE gui=reverse cterm=reverse
  hi TermCursorNC guifg=#fdf6e3 guibg=#93a1a1 guisp=NONE gui=NONE cterm=NONE
  hi Terminal guifg=fg guibg=#fdf6e3 guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Todo guifg=#d33682 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi ToolbarButton guifg=#586e75 guibg=#eee8d5 guisp=NONE gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=#eee8d5 guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#b58900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#6c71c4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#586e75 guibg=#93a1a1 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#93a1a1 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi VisualMode guifg=#d33682 guibg=#fdf6e3 guisp=NONE gui=reverse cterm=reverse
  hi VisualNOS guifg=NONE guibg=#eee8d5 guisp=NONE gui=reverse cterm=reverse
  hi WarningMsg guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi WildMenu guifg=#073642 guibg=#eee8d5 guisp=NONE gui=reverse cterm=reverse

  if has('gui_running')
    if s:diffmode == "high"
      hi DiffAdd guifg=#859900 guibg=NONE guisp=NONE gui=reverse
      hi DiffChange guifg=#b58900 guibg=NONE guisp=NONE gui=reverse
      hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=reverse
      hi DiffText guifg=#268bd2 guibg=NONE guisp=NONE gui=reverse
    elseif s:diffmode == "low"
      hi DiffAdd guifg=#859900 guibg=NONE guisp=#859900 gui=NONE
      hi DiffChange guifg=#b58900 guibg=NONE guisp=#b58900 gui=NONE
      hi DiffDelete guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi DiffText guifg=#268bd2 guibg=NONE guisp=#268bd2 gui=NONE
    endif
    if s:italics == 0
      hi Comment gui=NONE
    endif
    if s:stl == "flat"
      hi StatusLine guifg=#eee8d5 guibg=#073642 guisp=NONE gui=reverse
      hi StatusLineNC guifg=#eee8d5 guibg=#586e75 guisp=NONE gui=reverse
      hi TabLine guifg=#93a1a1 guibg=#eee8d5 guisp=NONE gui=NONE
      hi TabLineFill guifg=#93a1a1 guibg=#eee8d5 guisp=NONE gui=NONE
      hi TabLineSel guifg=#073642 guibg=#eee8d5 guisp=NONE gui=NONE
      hi VertSplit guifg=#93a1a1 guibg=#eee8d5 guisp=NONE gui=NONE
      hi WildMenu guifg=#839496 guibg=#fdf6e3 guisp=NONE gui=reverse
    elseif s:stl == "low"
      hi StatusLine guifg=#93a1a1 guibg=#fdf6e3 guisp=NONE gui=reverse
      hi StatusLineNC guifg=#93a1a1 guibg=#586e75 guisp=NONE gui=reverse
      hi TabLine guifg=#93a1a1 guibg=#586e75 guisp=NONE gui=reverse
      hi TabLineFill guifg=#93a1a1 guibg=#586e75 guisp=NONE gui=reverse
      hi TabLineSel guifg=#586e75 guibg=#fdf6e3 guisp=NONE gui=reverse
      hi VertSplit guifg=#586e75 guibg=#93a1a1 guisp=NONE gui=NONE
      hi WildMenu guifg=#586e75 guibg=#fdf6e3 guisp=NONE gui=reverse
    endif
    if s:transvis == 1
      hi CursorLineNr guifg=#657b83 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#839496 guibg=NONE guisp=NONE gui=NONE
    elseif s:transvis == 2
      hi CursorLineNr guifg=#dc322f guibg=#eee8d5 guisp=NONE gui=bold
      hi LineNr guifg=#657b83 guibg=#eee8d5 guisp=NONE gui=NONE
    elseif s:transvis == 3
      hi CursorLineNr guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#657b83 guibg=NONE guisp=NONE gui=NONE
    elseif s:transvis == 4
      hi CursorLineNr guifg=#93a1a1 guibg=#eee8d5 guisp=NONE gui=bold
      hi LineNr guifg=#93a1a1 guibg=#eee8d5 guisp=NONE gui=NONE
    elseif s:transvis == 5
      hi CursorLineNr guifg=#93a1a1 guibg=NONE guisp=NONE gui=bold
      hi LineNr guifg=#93a1a1 guibg=NONE guisp=NONE gui=NONE
    endif
    if s:viscurs == 1
      hi Cursor guifg=#fdf6e3 guibg=#657b83 guisp=NONE gui=NONE
    elseif s:viscurs == 2
      hi Cursor guifg=#fdf6e3 guibg=#dc322f guisp=NONE gui=NONE
    elseif s:viscurs == 3
      hi Cursor guifg=#fdf6e3 guibg=#657b83 guisp=NONE gui=NONE
    elseif s:viscurs == 4
      hi Cursor guifg=#fdf6e3 guibg=#cb4b16 guisp=NONE gui=NONE
    elseif s:viscurs == 5
      hi Cursor guifg=#fdf6e3 guibg=#657b83 guisp=NONE gui=NONE
    endif
    if s:visibility == "high"
      hi MatchParen guifg=#fdf6e3 guibg=#839496 guisp=NONE gui=bold
      hi NonText guifg=#dc322f guibg=NONE guisp=NONE gui=bold
      hi SpecialKey guifg=#dc322f guibg=NONE guisp=NONE gui=reverse
      hi SpellBad guifg=#d33682 guibg=#fdf6e3 guisp=#6c71c4 gui=reverse,undercurl
      hi SpellCap guifg=#d33682 guibg=#fdf6e3 guisp=#6c71c4 gui=reverse,undercurl
      hi SpellLocal guifg=#b58900 guibg=#fdf6e3 guisp=#cb4b16 gui=reverse,undercurl
      hi SpellRare guifg=#2aa198 guibg=#fdf6e3 guisp=#cb4b16 gui=reverse,undercurl
      hi Title guifg=#cb4b16 guibg=NONE guisp=NONE gui=bold
    elseif s:visibility == "low"
      hi MatchParen guifg=#dc322f guibg=#eee8d5 guisp=NONE gui=bold,underline
      hi NonText guifg=#eee8d5 guibg=NONE guisp=NONE gui=bold
      hi SpecialKey guifg=#eee8d5 guibg=NONE guisp=NONE gui=bold
      hi SpellBad guifg=#d33682 guibg=NONE guisp=#6c71c4 gui=undercurl
      hi SpellCap guifg=#d33682 guibg=NONE guisp=#6c71c4 gui=undercurl
      hi SpellLocal guifg=#b58900 guibg=NONE guisp=#b58900 gui=undercurl
      hi SpellRare guifg=#2aa198 guibg=NONE guisp=#2aa198 gui=undercurl
      hi Title guifg=#93a1a1 guibg=NONE guisp=NONE gui=bold
    endif
  endif

  if s:t_Co >= 256
    hi Normal ctermfg=242 ctermbg=230 ctermul=NONE cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=254 ctermul=NONE cterm=NONE
    hi CommandMode ctermfg=162 ctermbg=230 ctermul=NONE cterm=reverse
    hi Comment ctermfg=247 ctermbg=NONE ctermul=NONE cterm=italic
    hi Conceal ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Constant ctermfg=37 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Cursor ctermfg=230 ctermbg=166 ctermul=NONE cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=254 ctermul=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg ctermul=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=254 ctermul=NONE cterm=NONE
    hi CursorLineNr ctermfg=66 ctermbg=254 ctermul=NONE cterm=bold
    hi DiffAdd ctermfg=106 ctermbg=254 ctermul=NONE cterm=NONE
    hi DiffChange ctermfg=136 ctermbg=254 ctermul=NONE cterm=NONE
    hi DiffDelete ctermfg=160 ctermbg=254 ctermul=NONE cterm=bold
    hi DiffText ctermfg=32 ctermbg=254 ctermul=NONE cterm=NONE
    hi Directory ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi Error ctermfg=160 ctermbg=230 ctermul=NONE cterm=bold,reverse
    hi ErrorMsg ctermfg=160 ctermbg=230 ctermul=NONE cterm=reverse
    hi FoldColumn ctermfg=66 ctermbg=254 ctermul=NONE cterm=NONE
    hi Folded ctermfg=66 ctermbg=254 ctermul=NONE cterm=bold
    hi Identifier ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi IncSearch ctermfg=166 ctermbg=NONE ctermul=NONE cterm=standout
    hi InsertMode ctermfg=37 ctermbg=230 ctermul=NONE cterm=reverse
    hi LineNr ctermfg=246 ctermbg=254 ctermul=NONE cterm=NONE
    hi MatchParen ctermfg=160 ctermbg=254 ctermul=NONE cterm=bold,underline
    hi ModeMsg ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi MoreMsg ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    hi NonText ctermfg=246 ctermbg=NONE ctermul=NONE cterm=bold
    hi NormalMode ctermfg=242 ctermbg=230 ctermul=NONE cterm=reverse
    hi Pmenu ctermfg=242 ctermbg=254 ctermul=NONE cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=247 ctermul=NONE cterm=NONE
    hi PmenuSel ctermfg=254 ctermbg=246 ctermul=NONE cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=66 ctermul=NONE cterm=NONE
    hi PreProc ctermfg=166 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Question ctermfg=37 ctermbg=NONE ctermul=NONE cterm=bold
    hi ReplaceMode ctermfg=166 ctermbg=230 ctermul=NONE cterm=reverse
    hi Search ctermfg=136 ctermbg=NONE ctermul=NONE cterm=reverse
    hi SignColumn ctermfg=66 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Special ctermfg=166 ctermbg=NONE ctermul=NONE cterm=NONE
    hi SpecialKey ctermfg=246 ctermbg=254 ctermul=NONE cterm=bold
    hi SpellBad ctermfg=162 ctermbg=NONE ctermul=61 cterm=underline
    hi SpellCap ctermfg=162 ctermbg=NONE ctermul=61 cterm=underline
    hi SpellLocal ctermfg=136 ctermbg=NONE ctermul=136 cterm=underline
    hi SpellRare ctermfg=37 ctermbg=NONE ctermul=37 cterm=underline
    hi Statement ctermfg=106 ctermbg=NONE ctermul=NONE cterm=NONE
    hi StatusLine ctermfg=242 ctermbg=254 ctermul=NONE cterm=reverse
    hi StatusLineNC ctermfg=246 ctermbg=254 ctermul=NONE cterm=reverse
    hi TabLine ctermfg=246 ctermbg=254 ctermul=NONE cterm=reverse
    hi TabLineFill ctermfg=246 ctermbg=254 ctermul=NONE cterm=reverse
    hi TabLineSel ctermfg=242 ctermbg=254 ctermul=NONE cterm=reverse
    hi TermCursorNC ctermfg=230 ctermbg=247 ctermul=NONE cterm=NONE
    hi Terminal ctermfg=fg ctermbg=230 ctermul=NONE cterm=NONE
    hi Title ctermfg=166 ctermbg=NONE ctermul=NONE cterm=bold
    hi Todo ctermfg=162 ctermbg=NONE ctermul=NONE cterm=bold
    hi ToolbarButton ctermfg=242 ctermbg=254 ctermul=NONE cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=254 ctermul=NONE cterm=NONE
    hi Type ctermfg=136 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Underlined ctermfg=61 ctermbg=NONE ctermul=NONE cterm=NONE
    hi VertSplit ctermfg=242 ctermbg=247 ctermul=NONE cterm=NONE
    hi Visual ctermfg=247 ctermbg=230 ctermul=NONE cterm=reverse
    hi VisualMode ctermfg=162 ctermbg=230 ctermul=NONE cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=254 ctermul=NONE cterm=reverse
    hi WarningMsg ctermfg=166 ctermbg=NONE ctermul=NONE cterm=bold
    hi WildMenu ctermfg=236 ctermbg=254 ctermul=NONE cterm=reverse
    if s:diffmode == "high"
      hi DiffAdd ctermfg=106 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffChange ctermfg=136 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffDelete ctermfg=160 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffText ctermfg=32 ctermbg=NONE ctermul=NONE cterm=reverse
    elseif s:diffmode == "low"
      hi DiffAdd ctermfg=106 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffChange ctermfg=136 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffDelete ctermfg=160 ctermbg=NONE ctermul=NONE cterm=bold
      hi DiffText ctermfg=32 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:italics == 0
      hi Comment cterm=NONE
    endif
    if s:stl == "flat"
      hi StatusLine ctermfg=254 ctermbg=236 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=254 ctermbg=242 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=247 ctermbg=254 ctermul=NONE cterm=NONE
      hi TabLineFill ctermfg=247 ctermbg=254 ctermul=NONE cterm=NONE
      hi TabLineSel ctermfg=236 ctermbg=254 ctermul=NONE cterm=NONE
      hi VertSplit ctermfg=247 ctermbg=254 ctermul=NONE cterm=NONE
      hi WildMenu ctermfg=246 ctermbg=230 ctermul=NONE cterm=reverse
    elseif s:stl == "low"
      hi StatusLine ctermfg=247 ctermbg=230 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=247 ctermbg=242 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=247 ctermbg=242 ctermul=NONE cterm=reverse
      hi TabLineFill ctermfg=247 ctermbg=242 ctermul=NONE cterm=reverse
      hi TabLineSel ctermfg=242 ctermbg=230 ctermul=NONE cterm=reverse
      hi VertSplit ctermfg=242 ctermbg=247 ctermul=NONE cterm=NONE
      hi WildMenu ctermfg=242 ctermbg=230 ctermul=NONE cterm=reverse
    endif
    if s:termtrans == 1
      hi Normal ctermfg=242 ctermbg=NONE ctermul=NONE cterm=NONE
      hi FoldColumn ctermfg=66 ctermbg=NONE ctermul=NONE cterm=NONE
      hi Folded ctermfg=66 ctermbg=NONE ctermul=NONE cterm=bold
      hi Terminal ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE
      hi ToolbarButton ctermfg=242 ctermbg=NONE ctermul=NONE cterm=bold
      hi ToolbarLine ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:transvis == 1
      hi CursorLineNr ctermfg=66 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=246 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 2
      hi CursorLineNr ctermfg=160 ctermbg=254 ctermul=NONE cterm=bold
      hi LineNr ctermfg=66 ctermbg=254 ctermul=NONE cterm=NONE
    elseif s:transvis == 3
      hi CursorLineNr ctermfg=160 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=66 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 4
      hi CursorLineNr ctermfg=247 ctermbg=254 ctermul=NONE cterm=bold
      hi LineNr ctermfg=247 ctermbg=254 ctermul=NONE cterm=NONE
    elseif s:transvis == 5
      hi CursorLineNr ctermfg=247 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=247 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:viscurs == 1
      hi Cursor ctermfg=230 ctermbg=66 ctermul=NONE cterm=NONE
    elseif s:viscurs == 2
      hi Cursor ctermfg=230 ctermbg=160 ctermul=NONE cterm=NONE
    elseif s:viscurs == 3
      hi Cursor ctermfg=230 ctermbg=66 ctermul=NONE cterm=NONE
    elseif s:viscurs == 4
      hi Cursor ctermfg=230 ctermbg=166 ctermul=NONE cterm=NONE
    elseif s:viscurs == 5
      hi Cursor ctermfg=230 ctermbg=66 ctermul=NONE cterm=NONE
    endif
    if s:visibility == "high"
      hi MatchParen ctermfg=230 ctermbg=246 ctermul=NONE cterm=bold
      hi NonText ctermfg=160 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=160 ctermbg=NONE ctermul=NONE cterm=reverse
      hi SpellBad ctermfg=162 ctermbg=230 ctermul=61 cterm=reverse,underline
      hi SpellCap ctermfg=162 ctermbg=230 ctermul=61 cterm=reverse,underline
      hi SpellLocal ctermfg=136 ctermbg=230 ctermul=166 cterm=reverse,underline
      hi SpellRare ctermfg=37 ctermbg=230 ctermul=166 cterm=reverse,underline
      hi Title ctermfg=166 ctermbg=NONE ctermul=NONE cterm=bold
    elseif s:visibility == "low"
      hi MatchParen ctermfg=160 ctermbg=254 ctermul=NONE cterm=bold,underline
      hi NonText ctermfg=254 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=254 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpellBad ctermfg=162 ctermbg=NONE ctermul=61 cterm=underline
      hi SpellCap ctermfg=162 ctermbg=NONE ctermul=61 cterm=underline
      hi SpellLocal ctermfg=136 ctermbg=NONE ctermul=136 cterm=underline
      hi SpellRare ctermfg=37 ctermbg=NONE ctermul=37 cterm=underline
      hi Title ctermfg=247 ctermbg=NONE ctermul=NONE cterm=bold
    endif
    unlet s:t_Co
    unlet s:italics
    unlet s:termtrans
    unlet s:visibility
    unlet s:vismap
    unlet s:transvis
    unlet s:diffmode
    unlet s:stl
    unlet s:viscurs
    finish
  endif

  if s:t_Co >= 16
    hi Normal ctermfg=10 ctermbg=15 ctermul=NONE cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=7 ctermul=NONE cterm=NONE
    hi CommandMode ctermfg=5 ctermbg=15 ctermul=NONE cterm=reverse
    hi Comment ctermfg=14 ctermbg=NONE ctermul=NONE cterm=italic
    hi Conceal ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Constant ctermfg=6 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Cursor ctermfg=15 ctermbg=9 ctermul=NONE cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=7 ctermul=NONE cterm=NONE
    hi CursorIM ctermfg=NONE ctermbg=fg ctermul=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=7 ctermul=NONE cterm=NONE
    hi CursorLineNr ctermfg=11 ctermbg=7 ctermul=NONE cterm=bold
    hi DiffAdd ctermfg=2 ctermbg=7 ctermul=NONE cterm=NONE
    hi DiffChange ctermfg=3 ctermbg=7 ctermul=NONE cterm=NONE
    hi DiffDelete ctermfg=1 ctermbg=7 ctermul=NONE cterm=bold
    hi DiffText ctermfg=4 ctermbg=7 ctermul=NONE cterm=NONE
    hi Directory ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi EndOfBuffer ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi Error ctermfg=1 ctermbg=15 ctermul=NONE cterm=bold,reverse
    hi ErrorMsg ctermfg=1 ctermbg=15 ctermul=NONE cterm=reverse
    hi FoldColumn ctermfg=11 ctermbg=7 ctermul=NONE cterm=NONE
    hi Folded ctermfg=11 ctermbg=7 ctermul=NONE cterm=bold
    hi Identifier ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    hi IncSearch ctermfg=9 ctermbg=NONE ctermul=NONE cterm=standout
    hi InsertMode ctermfg=6 ctermbg=15 ctermul=NONE cterm=reverse
    hi LineNr ctermfg=12 ctermbg=7 ctermul=NONE cterm=NONE
    hi MatchParen ctermfg=1 ctermbg=7 ctermul=NONE cterm=bold,underline
    hi ModeMsg ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi MoreMsg ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    hi NonText ctermfg=12 ctermbg=NONE ctermul=NONE cterm=bold
    hi NormalMode ctermfg=10 ctermbg=15 ctermul=NONE cterm=reverse
    hi Pmenu ctermfg=10 ctermbg=7 ctermul=NONE cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=14 ctermul=NONE cterm=NONE
    hi PmenuSel ctermfg=7 ctermbg=12 ctermul=NONE cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=11 ctermul=NONE cterm=NONE
    hi PreProc ctermfg=9 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Question ctermfg=6 ctermbg=NONE ctermul=NONE cterm=bold
    hi ReplaceMode ctermfg=9 ctermbg=15 ctermul=NONE cterm=reverse
    hi Search ctermfg=3 ctermbg=NONE ctermul=NONE cterm=reverse
    hi SignColumn ctermfg=11 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Special ctermfg=9 ctermbg=NONE ctermul=NONE cterm=NONE
    hi SpecialKey ctermfg=12 ctermbg=7 ctermul=NONE cterm=bold
    hi SpellBad ctermfg=5 ctermbg=NONE ctermul=13 cterm=underline
    hi SpellCap ctermfg=5 ctermbg=NONE ctermul=13 cterm=underline
    hi SpellLocal ctermfg=3 ctermbg=NONE ctermul=3 cterm=underline
    hi SpellRare ctermfg=6 ctermbg=NONE ctermul=6 cterm=underline
    hi Statement ctermfg=2 ctermbg=NONE ctermul=NONE cterm=NONE
    hi StatusLine ctermfg=10 ctermbg=7 ctermul=NONE cterm=reverse
    hi StatusLineNC ctermfg=12 ctermbg=7 ctermul=NONE cterm=reverse
    hi TabLine ctermfg=12 ctermbg=7 ctermul=NONE cterm=reverse
    hi TabLineFill ctermfg=12 ctermbg=7 ctermul=NONE cterm=reverse
    hi TabLineSel ctermfg=10 ctermbg=7 ctermul=NONE cterm=reverse
    hi TermCursorNC ctermfg=15 ctermbg=14 ctermul=NONE cterm=NONE
    hi Terminal ctermfg=fg ctermbg=15 ctermul=NONE cterm=NONE
    hi Title ctermfg=9 ctermbg=NONE ctermul=NONE cterm=bold
    hi Todo ctermfg=5 ctermbg=NONE ctermul=NONE cterm=bold
    hi ToolbarButton ctermfg=10 ctermbg=7 ctermul=NONE cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=7 ctermul=NONE cterm=NONE
    hi Type ctermfg=3 ctermbg=NONE ctermul=NONE cterm=NONE
    hi Underlined ctermfg=13 ctermbg=NONE ctermul=NONE cterm=NONE
    hi VertSplit ctermfg=10 ctermbg=14 ctermul=NONE cterm=NONE
    hi Visual ctermfg=14 ctermbg=15 ctermul=NONE cterm=reverse
    hi VisualMode ctermfg=5 ctermbg=15 ctermul=NONE cterm=reverse
    hi VisualNOS ctermfg=NONE ctermbg=7 ctermul=NONE cterm=reverse
    hi WarningMsg ctermfg=9 ctermbg=NONE ctermul=NONE cterm=bold
    hi WildMenu ctermfg=0 ctermbg=7 ctermul=NONE cterm=reverse
    if s:diffmode == "high"
      hi DiffAdd ctermfg=2 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffChange ctermfg=3 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffDelete ctermfg=1 ctermbg=NONE ctermul=NONE cterm=reverse
      hi DiffText ctermfg=4 ctermbg=NONE ctermul=NONE cterm=reverse
    elseif s:diffmode == "low"
      hi DiffAdd ctermfg=2 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffChange ctermfg=3 ctermbg=NONE ctermul=NONE cterm=NONE
      hi DiffDelete ctermfg=1 ctermbg=NONE ctermul=NONE cterm=bold
      hi DiffText ctermfg=4 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:italics == 0
      hi Comment cterm=NONE
    endif
    if s:stl == "flat"
      hi StatusLine ctermfg=7 ctermbg=0 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=7 ctermbg=10 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=14 ctermbg=7 ctermul=NONE cterm=NONE
      hi TabLineFill ctermfg=14 ctermbg=7 ctermul=NONE cterm=NONE
      hi TabLineSel ctermfg=0 ctermbg=7 ctermul=NONE cterm=NONE
      hi VertSplit ctermfg=14 ctermbg=7 ctermul=NONE cterm=NONE
      hi WildMenu ctermfg=12 ctermbg=15 ctermul=NONE cterm=reverse
    elseif s:stl == "low"
      hi StatusLine ctermfg=14 ctermbg=15 ctermul=NONE cterm=reverse
      hi StatusLineNC ctermfg=14 ctermbg=10 ctermul=NONE cterm=reverse
      hi TabLine ctermfg=14 ctermbg=10 ctermul=NONE cterm=reverse
      hi TabLineFill ctermfg=14 ctermbg=10 ctermul=NONE cterm=reverse
      hi TabLineSel ctermfg=10 ctermbg=15 ctermul=NONE cterm=reverse
      hi VertSplit ctermfg=10 ctermbg=14 ctermul=NONE cterm=NONE
      hi WildMenu ctermfg=10 ctermbg=15 ctermul=NONE cterm=reverse
    endif
    if s:termtrans == 1
      hi Normal ctermfg=10 ctermbg=NONE ctermul=NONE cterm=NONE
      hi FoldColumn ctermfg=11 ctermbg=NONE ctermul=NONE cterm=NONE
      hi Folded ctermfg=11 ctermbg=NONE ctermul=NONE cterm=bold
      hi Terminal ctermfg=fg ctermbg=NONE ctermul=NONE cterm=NONE
      hi ToolbarButton ctermfg=10 ctermbg=NONE ctermul=NONE cterm=bold
      hi ToolbarLine ctermfg=NONE ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:transvis == 1
      hi CursorLineNr ctermfg=11 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=12 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 2
      hi CursorLineNr ctermfg=1 ctermbg=7 ctermul=NONE cterm=bold
      hi LineNr ctermfg=11 ctermbg=7 ctermul=NONE cterm=NONE
    elseif s:transvis == 3
      hi CursorLineNr ctermfg=1 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=11 ctermbg=NONE ctermul=NONE cterm=NONE
    elseif s:transvis == 4
      hi CursorLineNr ctermfg=14 ctermbg=7 ctermul=NONE cterm=bold
      hi LineNr ctermfg=14 ctermbg=7 ctermul=NONE cterm=NONE
    elseif s:transvis == 5
      hi CursorLineNr ctermfg=14 ctermbg=NONE ctermul=NONE cterm=bold
      hi LineNr ctermfg=14 ctermbg=NONE ctermul=NONE cterm=NONE
    endif
    if s:viscurs == 1
      hi Cursor ctermfg=15 ctermbg=11 ctermul=NONE cterm=NONE
    elseif s:viscurs == 2
      hi Cursor ctermfg=15 ctermbg=1 ctermul=NONE cterm=NONE
    elseif s:viscurs == 3
      hi Cursor ctermfg=15 ctermbg=11 ctermul=NONE cterm=NONE
    elseif s:viscurs == 4
      hi Cursor ctermfg=15 ctermbg=9 ctermul=NONE cterm=NONE
    elseif s:viscurs == 5
      hi Cursor ctermfg=15 ctermbg=11 ctermul=NONE cterm=NONE
    endif
    if s:visibility == "high"
      hi MatchParen ctermfg=15 ctermbg=12 ctermul=NONE cterm=bold
      hi NonText ctermfg=1 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=1 ctermbg=NONE ctermul=NONE cterm=reverse
      hi SpellBad ctermfg=5 ctermbg=15 ctermul=13 cterm=reverse,underline
      hi SpellCap ctermfg=5 ctermbg=15 ctermul=13 cterm=reverse,underline
      hi SpellLocal ctermfg=3 ctermbg=15 ctermul=9 cterm=reverse,underline
      hi SpellRare ctermfg=6 ctermbg=15 ctermul=9 cterm=reverse,underline
      hi Title ctermfg=9 ctermbg=NONE ctermul=NONE cterm=bold
    elseif s:visibility == "low"
      hi MatchParen ctermfg=1 ctermbg=7 ctermul=NONE cterm=bold,underline
      hi NonText ctermfg=7 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpecialKey ctermfg=7 ctermbg=NONE ctermul=NONE cterm=bold
      hi SpellBad ctermfg=5 ctermbg=NONE ctermul=13 cterm=underline
      hi SpellCap ctermfg=5 ctermbg=NONE ctermul=13 cterm=underline
      hi SpellLocal ctermfg=3 ctermbg=NONE ctermul=3 cterm=underline
      hi SpellRare ctermfg=6 ctermbg=NONE ctermul=6 cterm=underline
      hi Title ctermfg=14 ctermbg=NONE ctermul=NONE cterm=bold
    endif
    unlet s:t_Co
    unlet s:italics
    unlet s:termtrans
    unlet s:visibility
    unlet s:vismap
    unlet s:transvis
    unlet s:diffmode
    unlet s:stl
    unlet s:viscurs
    finish
  endif

  if s:t_Co >= 0
    hi Normal term=NONE
    hi ColorColumn term=reverse
    hi CommandMode term=reverse
    hi Comment term=italic
    hi Conceal term=NONE
    hi Constant term=bold,italic
    hi Cursor term=NONE
    hi CursorColumn term=reverse
    hi CursorIM term=NONE
    hi CursorLine term=underline
    hi CursorLineNr term=bold,italic,reverse,underline
    hi DiffAdd term=reverse,underline
    hi DiffChange term=reverse,underline
    hi DiffDelete term=reverse,underline
    hi DiffText term=bold,reverse,underline
    hi Directory term=NONE
    hi EndOfBuffer term=NONE
    hi Error term=reverse
    hi ErrorMsg term=bold,italic,reverse
    hi FoldColumn term=reverse
    hi Folded term=italic,reverse,underline
    hi Identifier term=italic
    hi Ignore term=NONE
    hi IncSearch term=bold,italic,reverse
    hi InsertMode term=reverse
    hi LineNr term=reverse
    hi MatchParen term=bold,underline
    hi ModeMsg term=NONE
    hi MoreMsg term=NONE
    hi NonText term=NONE
    hi NormalMode term=reverse
    hi Pmenu term=reverse
    hi PmenuSbar term=NONE
    hi PmenuSel term=NONE
    hi PmenuThumb term=NONE
    hi PreProc term=italic
    hi Question term=standout
    hi ReplaceMode term=reverse
    hi Search term=italic,underline
    hi SignColumn term=reverse
    hi Special term=bold,italic
    hi SpecialKey term=bold
    hi SpellBad term=italic,underline
    hi SpellCap term=italic,underline
    hi SpellLocal term=italic,underline
    hi SpellRare term=italic,underline
    hi Statement term=bold
    hi StatusLine term=bold,reverse
    hi StatusLineNC term=reverse
    hi TabLine term=italic,reverse,underline
    hi TabLineFill term=reverse,underline
    hi TabLineSel term=bold
    hi TermCursorNC term=NONE
    hi Terminal term=NONE
    hi Title term=bold
    hi Todo term=bold,underline
    hi ToolbarButton term=bold,reverse
    hi ToolbarLine term=reverse
    hi Type term=bold
    hi Underlined term=underline
    hi VertSplit term=reverse
    hi Visual term=reverse
    hi VisualMode term=reverse
    hi VisualNOS term=NONE
    hi WarningMsg term=standout
    hi WildMenu term=bold
    if s:diffmode == "high"
      hi DiffAdd term=reverse
      hi DiffChange term=reverse
      hi DiffDelete term=reverse
      hi DiffText term=reverse
    elseif s:diffmode == "low"
      hi DiffDelete term=bold
    endif
    if s:italics == 0
      hi Comment term=NONE
    endif
    if s:stl == "flat"
      hi StatusLine term=reverse
      hi StatusLineNC term=reverse
      hi TabLine term=NONE
      hi TabLineFill term=NONE
      hi TabLineSel term=NONE
      hi VertSplit term=NONE
      hi WildMenu term=reverse
    elseif s:stl == "low"
      hi StatusLine term=reverse
      hi StatusLineNC term=reverse
      hi TabLine term=reverse
      hi TabLineFill term=reverse
      hi TabLineSel term=reverse
      hi VertSplit term=NONE
      hi WildMenu term=reverse
    endif
    if s:transvis == 1
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 2
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 3
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 4
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    elseif s:transvis == 5
      hi CursorLineNr term=bold
      hi LineNr term=NONE
    endif
    if s:viscurs == 1
      hi Cursor term=NONE
    elseif s:viscurs == 2
      hi Cursor term=NONE
    elseif s:viscurs == 3
      hi Cursor term=NONE
    elseif s:viscurs == 4
      hi Cursor term=NONE
    elseif s:viscurs == 5
      hi Cursor term=NONE
    endif
    if s:visibility == "high"
      hi MatchParen term=bold
      hi NonText term=bold
      hi SpecialKey term=reverse
      hi Title term=bold
    elseif s:visibility == "low"
      hi MatchParen term=bold,underline
      hi NonText term=bold
      hi SpecialKey term=bold
      hi Title term=bold
    endif
    unlet s:t_Co
    unlet s:italics
    unlet s:termtrans
    unlet s:visibility
    unlet s:vismap
    unlet s:transvis
    unlet s:diffmode
    unlet s:stl
    unlet s:viscurs
    finish
  endif
endif

" vim: nowrap et sw=2
